WINDOW_WIDTH = 560
MODE_SELECTOR_HEIGHT = 50
CONTROLS_FRAME_HEIGHT = 80
KEYBOARD_HEIGHT = 160
SCORE_DISPLAY_HEIGHT = 110
WINDOW_HEIGHT = KEYBOARD_HEIGHT + CONTROLS_FRAME_HEIGHT + MODE_SELECTOR_HEIGHT  + SCORE_DISPLAY_HEIGHT


CHOICES = ['Scales','Chords','Chord Progressions']
